---
title: "CPT_CCS"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(janitor)
library(DataExplorer)
```

## TO DO

 - Deal with alphanumeric codes (pull out [a-z]? then merge back?)
 - Create explict codes within range

## WORKING

```{r import-hcpcs, warning=FALSE}
hcpcs_src <- readxl::read_xlsx("~/unch-charges/data/HCPCS/HCPC2021_OCT_ANWEB.xlsx")

betos_src <- read_csv("~/unch-charges/data/betos.csv",
                    #clean column names
                    name_repair = janitor::make_clean_names)

nc_crosswalk_src <- read_csv("~/unch-charges/data/nc_crosswalk.csv")
```

```{r counts}
betos_count <- hcpcs_src %>%
  distinct(BETOS) %>%
  count()

nc_crosswalk_src <- clean_names(nc_crosswalk_src)

category <- nc_crosswalk_src %>%
  group_by(description) %>%
  distinct(description)

```

```{r betos}
betos_src %>% head()

betos_xwalk <- hcpcs_src %>%
  inner_join(betos_src, by = c("BETOS" = "permissible_value"), keep = TRUE)

betos_xwalk <- clean_names(betos_xwalk)
```

```{r join-charges-category}
charge_cat <- charges_long %>%
  inner_join(nc_crosswalk_src, by = c("cpt_hcpcs" = "code"), keep = TRUE)
```

```{r}
introduce(charge_cat)
charge_cat %>% plot_missing()
charge_cat %>% head()
```

```{r}
# Remove data we don't need 
charge_cat2 <- charge_cat %>%
  select(charge_description, cpt_hcpcs, price, payor, charge, description, op_srvc_ctg_short, ph_srvc_ctg_short)


ggplot(data = charge_cat2) +
  geom_bar(mapping = aes(x = fct_infreq(as.factor(description)))) +
  coord_flip() +
  labs(subtitle = "Quick Visualization")


```


```{r}
summary(lm(charge ~ factor(description), data = charge_cat2))
```
```{r}
summary(lm(price ~ factor(description), data = charge_cat2))
```

```{r}
skim(charge_cat2)
```


```{r payor-high}
payor_high <- charges_long %>% 
  arrange(desc(charge)) %>%
  group_by(payor) %>%
  slice_max(charge, n = 5, with_ties = FALSE)


  # group_by(payor, charge) %>% 
  # summarize()
```


```{r}
ggplot(payor_high, aes(x = charge_description, y = charge, color = payor)) +
    geom_boxplot()+
    geom_point(size = 2, position = position_jitter(width = 0.2)) +
          scale_x_discrete(label = function(x) stringr::str_trunc(x, 25)) +
    stat_summary(fun = mean, geom = "point", shape = 20, size = 6, color = "blue")+
    theme_classic() +
    theme(legend.position="none") +
        guides(x = guide_axis(angle = -20))
```

```{r quality-check}
plot_missing(charges_long, missing_only = TRUE)
introduce(charges_long)
plot_intro(charges_long)
profile_missing(charges_long)
```

```{r}
payor_test <- charges_long %>% 
  drop_na() %>%
  group_by(payor) %>%
  select(!cpt_hcpcs) %>%
  summarise(avg = mean(charge, na.rm=TRUE), mid = median(charge, na.rm=TRUE))

ggplot(payor_test, aes(avg, mid)) + 
  geom_point()
```


```{r}
payor_test2 <- charges_long %>% 
  drop_na() %>%
  group_by(payor) %>%
  distinct() %>%
  add_count(charge) %>%
  summarise(across(charge, sum)) %>%
  mutate(wt = charge / 5011)
  
p1 <- ggplot(data = payor_test2, mapping = aes(x = reorder(payor, charge), charge)) + 
  geom_bar(stat = "identity") + coord_flip()

p2 <- ggplot(data = payor_test2, mapping = aes(x = reorder(payor, wt), wt)) + 
  geom_bar(stat = "identity") + coord_flip()

p1
p2
```


























# OBSELETE
<!-- ```{r import-ccs-cpt} -->
<!-- <!-- cpt <- read_csv("~/unch-charges/data/CCS_ServicesProcedures_v2021-1/CCS_services_procedures_v2021-1.csv", skip = 1) --> -->
<!-- ``` -->



<!-- ```{r string-extract} -->
<!-- #x <- '61000-61001' -->

<!-- #str_extract_all(x, "\\w+") -->

<!-- y <- 'C1898-C1899' -->

<!-- var1 <- str_extract_all(y, "\\w+") -->
<!-- d <-  str_extract_all(var1, "[[:upper:]]+") -->

<!-- var1 -->
<!-- d -->


<!-- ``` -->

<!-- ```{r} -->
<!-- cpt_split_code_range <- cpt %>% -->
<!--   mutate( -->
<!--     remove_quote = str_replace_all(`Code Range`, "'", ""), -->
<!--     code_beg = str_extract_all(remove_quote, "\\w+", simplify = TRUE)[,1], -->
<!--     code_end = str_extract_all(remove_quote, "\\w+", simplify = TRUE)[,2], -->
<!--     alpha_prefix_beg = str_sub(code_beg, 1, 1), -->
<!--     alpha_rmdr_beg = str_sub(code_beg, 2), -->
<!--     alpha_prefix_end = str_sub(code_end, 1, 1), -->
<!--     alpha_rmdr_end = str_sub(code_end, 2) -->
<!--     ) -->


<!-- ``` -->

<!-- ```{r} -->
<!-- test <- as.numeric(c("9930", "9932")) -->
<!-- seq.int(test) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- cpt2 <- cpt %>% -->
<!--   mutate( -->
<!--     col1 = str_extract_all(`Code Range`, "\\w+")) -->


<!--     #col1 = str_extract_all('Code Range', "[[:upper:]]+")) -->

<!-- #, -->
<!-- ##    col2 = str_extract_all(col1, "\\w+") -->
<!-- #  ) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- SplitMe <- function(string, alphaFirst = TRUE) { -->
<!--   Pattern <- ifelse(isTRUE(alphaFirst), "(?<=[a-zA-Z])(?=[0-9])", "(?<=[0-9])(?=[a-zA-Z])") -->
<!--   strsplit(string, split = Pattern, perl = T) -->
<!-- } -->

<!-- String <- cpt$`Code Range` -->
<!-- SplitMe(String) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- cpt3 <- cpt %>% -->
<!--   mutate( -->
<!--     col4 = str_extract_all(`Code Range`, "[[:upper:]]+") -->
<!--   ) -->
<!-- ``` -->
