---
title: "main"
output: html_document
---

# Setup --------------------------------- 

```{r setup, echo=FALSE}
library(tidyverse)
library(janitor)
library(hrbrthemes)
library(ggridges)
library(ggrepel)
library(haven)
library(DataExplorer)
library(matlab)
library(quanteda)
library(tidytext)
```

# Load data ----------------------------- 

```{r warning=FALSE}
# Import data sources
charges <- read_csv("data/561118388_uncmedicalcenter_cdmstandardcharges.csv",
                name_repair = make_clean_names)

betos <- read_csv("~/unch-charges/data/betos.csv",
                name_repair = janitor::make_clean_names)

crosswalk <- read_csv("~/unch-charges/data/nc_crosswalk.csv",
                name_repair = janitor::make_clean_names)

hcpcs <- readxl::read_xlsx("~/unch-charges/data/HCPCS/HCPC2021_OCT_ANWEB.xlsx")
```
# Preprocess ---------------------------

```{r preprocess}

# Remove unnecessary strings and pivot long
charges_clean <- charges %>%
  select(!facility_name) %>%
  mutate(code = str_remove(cpt_hcpcs, "MS-DRG: "), .keep = "unused") %>%
  mutate(clean_description = str_remove(charge_description, "HC "),
         .keep = "unused") %>%
  pivot_longer(
    cols = aetna:united_healthcare_medicare_advantage,
    names_to = "payor",
    values_to = "charge",
  ) %>%
  mutate(is.medicare = map_lgl(payor, ~ any(str_detect(., "medicare")) | (str_detect(., "humana_alignment")))) %>% # Note to lookup each for medicare
  mutate(across(payor, as_factor)) %>%
  mutate(code = replace_na(code, "NO CODE")) %>%
  mutate(index_clean = 1:nrow(.)) %>%
  arrange(runif(nrow(.)))


# Remove $ and , from string, convert to numeric
charges_clean$price = as.double(gsub("[\\$,]", "", charges_clean$price))
charges_clean$min = as.double(gsub("[\\$,]", "", charges_clean$min))
charges_clean$max = as.double(gsub("[\\$,]", "", charges_clean$max))
charges_clean$charge = as.double(gsub("[\\$,]", "", charges_clean$charge))  

# regex for HC /^(?:HC )\b

unique_payor <- distinct(charges_clean, payor)


```

```{r feat}
# Add features for range and price/charge difference
charges_clean_ft <- charges_clean %>%
  filter(charge >= 1) %>%
  mutate(rng = max - min) %>%
  mutate(price_diff = charge - price)

# Output data changes
print(sprintf("Before simplification and deduplication: %d, after %d (%0.2f %% decrease)",
              nrow(charges_clean),
              nrow(charges_clean_ft),
              100-100*nrow(charges_clean_ft)/nrow(charges_clean)));

# Recode NA codes
# charges_clean_ft2 <- charges_clean_ft %>%
#   mutate(code = replace_na(code, "NO CODE")) 

```
```{r charge-catagories}
category <- charges_clean %>%
  inner_join(crosswalk, by = c("code" = "code"), keep = TRUE) %>%
  select(index_clean, clean_description, description)

print(sprintf("Before inner join: %d, after %d (%0.2f %% decrease)",
              nrow(charges_clean),
              nrow(category),
              100-100*nrow(category)/nrow(charges_clean)));

```



```{r crossref-catagories}
betos_hcpcs <- hcpcs %>%
  inner_join(betos, by = c("BETOS" = "permissible_value"), keep = TRUE)

betos_hcpcs <- clean_names(betos_hcpcs)

# unique_cat <- betos_hcpcs %>%
#   group_by(domain_meaning_name) %>%
#   distinct

betos_cat <- charges_clean %>%
  inner_join(betos_hcpcs, by = c("code" = "hcpc"), keep = TRUE) %>%
  select(clean_description, code, price, min, max, payor, charge, domain_meaning_name, long_description)

print(sprintf("Before simplification and join: %d, after %d (%0.2f %% decrease)",
              nrow(betos_hcpcs),
              nrow(charges_clean),
              100-100*nrow(charges_clean)/nrow(betos_hcpcs)));



# charge_cat <- charges_long %>%
#   inner_join(betos_hcpcs, by = c("code" = "hcpc"), keep = TRUE) %>%
#   select(charge_description, code, price, min, max, payor, charge, domain_meaning_name, long_description)
# 
# charge_cat_leftjoin <- charges_long %>%
#   left_join(betos_hcpcs, by = c("code" = "hcpc"), keep = TRUE) %>%
#   select(charge_description, code, price, min, max, payor, charge, domain_meaning_name, long_description) %>%
#   mutate(is.medicare = map_lgl(payor, ~any(str_detect(., "medicare"))))
# 
# # All charges as 0 to 1 for matrices
# charge_cat[charge_cat == 0] <- 1

# Convert back to wide data
charges_wide <- charges_long %>%
                  select(-facility_name, -cpt_hcpcs) %>%
                  pivot_wider(names_from = "payor",
                    values_from = "charge",
                    names_glue="{.value}_{payor}",
                    values_fill=0) %>%
                  mutate(index_cluster=1:nrow(.)) %>%
                  arrange(runif(nrow(.)));

# charge_cat_wide <- charges_wide %>%
#     inner_join(betos_hcpcs, by = c("code" = "hcpc"), keep = TRUE) %>%
#     select(starts_with("charge_"), code, price, min, max, index_cluster, domain_meaning_name, long_description)
# 
# charge_cat_wide_qualitycheck <- charges_wide %>%
#     left_join(betos_hcpcs, by = c("code" = "hcpc"), keep = TRUE) %>%
#     select(starts_with("charge_"), code, price, min, max, index_cluster, permissible_value, domain_meaning_name, long_description)
# 
# charge_cat_wide[charge_cat_wide == 0] <- 1
  
```

```{r EXPERIMENT}
test <- charges_long %>%
  inner_join(crosswalk, by = c("cpt_hcpcs" = "code"), keep = TRUE) %>%
  select(charge_description, code.x, price, min, max, payor, charge, description) %>%
  mutate(is.medicare = map_lgl(payor, ~any(str_detect(., "medicare"))))

# test_wide <- test %>%
#   pivot_wider(names_from = "payor",
#               values_from = "charge",
#               names_glue="{.value}_{payor}",
#               values_fill=0) %>%
#   mutate(index_cluster=1:nrow(.)) %>%
#   arrange(runif(nrow(.))) %>%
#   select(!is_medicare)

# Changes is_medicare to TRUE
# test[test == 0] <- 1
# 
# test_wide[test_wide == 0] <- 1

```

```{r}

ggplot(test) +
  geom_bar(mapping = aes(x = fct_infreq(as.factor(description)))) +
  coord_flip() +
  labs(subtitle = "Quick Visualization")

ggplot(test) +
  geom_bar(mapping = aes(x = is.medicare)) +
  coord_flip() +
  labs(subtitle = "Quick Visualization")

```





```{r}
check <- charge_cat %>%
  group_by(payor) %>%
  summarise(avg = mean(charge, na.rm=TRUE)) %>%
  arrange(desc(avg)) %>%
  filter(quantile(avg, 0.5)<avg)

ggplot(check, aes(x = payor, y = avg)) +
    geom_col() +
    coord_flip()
```

```{r}
lm1 <- lm(test$charge ~ test$is.medicare + test$description)
summary(lm1)
```



```{r}


# Replace numerical NA with column mean
# charges_wide2 <-  for (i in which(sapply(charges_wide, is.numeric))) {
  #   charges_wide[is.na(charges_wide[, i]), i] <- mean(charges_wide[, i],  na.rm = TRUE)
  # }

```



```{r pca}
charges_matrix <- charges_wide %>%
  select(-charge_description, -code) %>%
  as.matrix();

library(missMDA)
# estimate number of components
nb <- estim_ncpPCA(charges_matrix, ncp.min=0, ncp.max=5)
# actual impute
charges_wide_impute <- imputePCA(charges_matrix, ncp=nb$ncp)

pca_fit <- prcomp(charges_wide_impute$completeObs);
  pca_fit$rotation
pca_fit$rotation

summary(pca_fit)

library(factoextra)

res.pca <- prcomp(charges_wide_impute$completeObs, scale = TRUE)

fviz_eig(res.pca)

fviz_pca_ind(res.pca,
             col.ind = "cos2", 
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE)
```


```{r scatterplot warning=FALSE}
# charges_long %>%
#   select(price, payor, charge) %>% 
  
ggplot(charges_long, aes(x = price, y = charge, label = payor)) + 
    geom_point(aes(), size = 1, alpha = 0.1) +
    # Highlight procedures > $75,000 in red
    geom_point(data = charges_long[charges_long$charge > 75000,], alpha = 0.5, color = "red", size = 2,) +
    # Only label procedures > $75,000 and avoid overlap
    geom_text_repel(data = charges_long[charges_long$charge > 75000,], 
      size = 2.5,
      nudge_x = .15,
      box.padding = 0.5,
      nudge_y = 1,
      segment.curvature = -0.1,
      segment.ncp = 3,
      segment.angle = 20
      ) +
    # Add Title, subtitle and axis labels
    labs(title = "Prices vs. Charges ",
      subtitle="UNC Medical Center, Aug 2021",
      x = "Price",
      y = "Charge", 
      caption = "Source | UNC Health") + 
    # Add theme from hrbrthemes lib
    theme_ipsum_rc() + 
    coord_cartesian(clip = "off")
```

```{r ridgeplot warning=FALSE, message=FALSE}
ggplot(charges_long, aes(x = charge, y = payor)) +
  geom_density_ridges(rel_min_height = 0) +
  scale_y_discrete(expand = c(0, 0)) +
  scale_x_continuous(limits = c(1, 1000), expand = c(0, 0.01)) +
  scale_fill_brewer(palette = 4) +
    labs(
        x = "Charge (USD)",
        y = "Payor",
        title = "Healthcare Insurance Comparison",
        subtitle = "Healthcare Services (n = 5011)",
        caption = "Source | UNC Health") + 
  theme_ridges() + theme(legend.position = "none")
```

```{r}
summary(charges_long)
summary(charges_wide)
```


```{r}
charges_wide_matrix <- charges_wide %>%
  select_if(is.numeric) %>%
  select(!index_cluster) %>%
  arrange(desc(price), .by_group = TRUE) %>%
  as.matrix()
```


```{r}
heatmap(charges_wide_matrix, xlab="Payor", ylab="Charge Code", main="heatmap")
```


```{r}
p <- charges_long %>%
  select(payor, charge, price, code) %>%
  filter(payor == "bcbs" | payor == "bcbs_medicare_advantage" | payor == "bcbs_unc_health_alliance" | payor == "blue_home") %>%
  mutate(across(payor, as_factor))

ggplot(p, aes(x=price, y=charge, color=payor)) + 
  geom_point()
```

```{r lollipop }
ggplot(p, aes(x=payor, y=charge)) +
  geom_point() + 
  geom_segment( aes(x=payor, xend=1, y=0, yend=1000))
```


# Wrangle  ----------------------------


# Plot  -------------------------------


# Features  -------------------------------

```{r}
 # Scratch with 'test' data
test2 <- charge_cat_leftjoin %>%
  filter(charge > 0) %>%
  mutate(rng = max - min) %>%
  mutate(price_diff = charge - price)


print(sprintf("Before simplification and deduplication: %d, after %d (%0.2f %% decrease)",
              nrow(test),
              nrow(test2),
              100-100*nrow(test2)/nrow(test)));
         

```



# Text analysis ---------------------------

```{r}
# charges_txt2 <- charges %>%
#   mutate(index_cluster=1:nrow(.)) %>%
#   arrange(runif(nrow(.))) %>%
#   mutate(cleaned = str_remove(charge_description, "[a-zA-Z]+\s"))


# mycorp <- corpus(charges_txt$charge_description)
# 
# mytokens <- tokens(mycorp, remove_punct = TRUE, remove_numbers = TRUE)

# 
# texts(txt_charges)
# 
# txt_charges_quant <- corpus(charges)


# tokens(txt_charges)

# txt_charges %>%
#   count(word, sort = TRUE) %>%
#   filter(n > 150) %>%
#   mutate(word = reorder(word, n)) %>%
#   ggplot(aes(n, word)) +
#   geom_col() +
#   labs(y = NULL)
```


