---
title: "UNC Health Charges"
author: "Andrew Kant"
date: "8/25/2021"
output: html_document
---

```{r setup, echo=FALSE}
library(tidyverse)
library(janitor)
library(hrbrthemes)
library(ggridges)
library(ggrepel)
library(haven)
library(DataExplorer)
library(matlab)

charges <- read_csv("data/561118388_uncmedicalcenter_cdmstandardcharges.csv",
                    #clean column names
                    name_repair = make_clean_names)
```


```{r import-hcpcs, warning=FALSE}
hcpcs <- readxl::read_xlsx("~/unch-charges/data/HCPCS/HCPC2021_OCT_ANWEB.xlsx")
```




# Introduction


# Data

Let's take a quick look at the data with `glimpse`

```{r}
introduce(charges)
plot_intro(charges)
```

```{r missing}
plot_missing(charges)
```








So it looks like we have charge bundles, standard prices, ranges (min, max) and payor-specific charges in this dataset. 

## Wrangle

Let's organize Payor columns into a more manageable format.

```{r wrangle_col}
charges_long <- charges %>%
  # Wrangle payor columns to key:value pair
  pivot_longer(
    cols = aetna:united_healthcare_medicare_advantage,
    names_to = "payor",
    values_to = "charge",
    )

plot_missing(charges_long)
introduce(charges_long)
plot_intro(charges_long)
```


Looks like most our charge data is not numeric. 

```{r convert-charge-long}
# Remove $ and , from string, convert to numeric
charges_long$price = as.integer(gsub("[\\$,]", "", charges_long$price))
charges_long$min = as.integer(gsub("[\\$,]", "", charges_long$min))
charges_long$max = as.integer(gsub("[\\$,]", "", charges_long$max))
charges_long$charge = as.integer(gsub("[\\$,]", "", charges_long$charge))

plot_missing(charges_long)
introduce(charges_long)
```

```{r convert-charge-WARNING}
# Remove $ and , from string, convert to numeric
charges$price = as.integer(gsub("[\\$,]", "", charges$price))
charges$min = as.integer(gsub("[\\$,]", "", charges$min))
charges$max = as.integer(gsub("[\\$,]", "", charges$max))
charges$bcbs = as.integer(gsub("[\\$,]", "", charges$bcbs))
```

```{r charges-wider-WORKING}
charges_wide <- charges_long %>%
                  select(-facility_name) %>%
                  pivot_wider(names_from = "payor",
                    values_from = "charge",
                    names_glue="{.value}_{payor}",
                    values_fill=0) %>%
                  mutate(index_cluster=1:nrow(.)) %>%
                  arrange(runif(nrow(.)));


# Pivot Wider for matrix operations?
# charges_wide <- charges_long %>%
#     arrange(cpt_hcpcs) %>%
#     pivot_wider(id_cols=c("index_long","cpt_hcpcs"),
#                 names_from="payor",
#                 values_from="charge") %>%
#     mutate(index_cluster=1:nrow(.)) %>%
#     arrange(runif(nrow(.)));
```

```{r index}
# REVIEW Should index on original table and add before pivot_longer
charges <- tibble::rowid_to_column(charges, "index")
charges_long <- tibble::rowid_to_column(charges_long, "index_long")
```



```{r}
plot_histogram(charges_long)
```

```{r}
plot_correlation(na.omit(charges_long), maxcat = 5L)
```



```{r top10, warning = FALSE}
charges %>%
  select(index, price, charge_description, cpt_hcpcs) %>% 
  slice_max(price, n = 10) %>% 
  ggplot(., aes(), group = 10) + 
    geom_col(aes(x = charge_description, y = price)) + 
      scale_x_discrete(label = function(x) stringr::str_trunc(x, 25)) +
#coord_flip() + 
      labs(title = "Top 10 Most Expensive Procedures",
           subtitle="UNC Medical Center, Aug 2021",
           x = "",
           y = "Price (US Dollars)",
           caption = "Source | UNC Health") + 
      guides(x = guide_axis(angle = -20)) +
      theme_ipsum_rc()
```

```{r all-std-charges, warning = FALSE}
charges %>%
  select(index, price, charge_description, cpt_hcpcs) %>% 
  ggplot(aes(x = index, y = price, label = charge_description)) + 
    geom_point(aes(), size = 1, alpha = 0.1) +
    # Highlight procedures > $75,000 in red
    geom_point(data = charges[charges$price > 75000,], alpha = 0.5, color = "red", size = 2,) +
    # Only label procedures > $75,000 and avoid overlap
    geom_text_repel(data = charges[charges$price > 75000,], 
      size = 2.5,
      nudge_x = .15,
      box.padding = 0.5,
      nudge_y = 1,
      segment.curvature = -0.1,
      segment.ncp = 3,
      segment.angle = 20
      ) +
    # Add Title, subtitle and axis labels
    labs(title = "Charge Bundles at UNC Health",
      subtitle="UNC Medical Center, Aug 2021",
      x = "Procedure Code",
      y = "Price (US Dollars)", 
      caption = "Source | UNC Health") + 
    # Add theme from hrbrthemes lib
    theme_ipsum_rc() + 
    coord_cartesian(clip = "off")
```  

```{r payor-compare, warning = FALSE, message = FALSE}
ggplot(charges_cln, aes(x = charge, y = payor)) +
  geom_density_ridges(rel_min_height = 0.01) +
  scale_y_discrete(expand = c(0, 0)) +
  scale_x_continuous(limits = c(1, 750), expand = c(0, 0.01)) +
  scale_fill_brewer(palette = 4) +
    labs(
        x = "Price (USD)",
        y = "Payor",
        title = "Healthcare Insurance Comparison",
        subtitle = "Care Charge Bundles (n = 5011)",
        caption = "Source | UNC Health") + 
  theme_ridges() + theme(legend.position = "none")

```

# Clustering 

```{r clustering-prep}
# Pivot Wider for matrix operations?
charges_wide <- charges_long %>%
    arrange(cpt_hcpcs) %>%
    pivot_wider(id_cols=c("index_long","cpt_hcpcs"),
                names_from="payor",
                values_from="charge") %>%
    mutate(index_cluster=1:nrow(.)) %>%
    arrange(runif(nrow(.)));
```


```{r kmeans}


#Create matrix
price_matrix <- charges_wide %>% select(-charge_description, -cpt_hcpcs) %>% as.matrix();

# km_results <- kmeans(na.omit(price_matrix),3, nstart = 25)

price_matrix_valid <- na.omit(price_matrix)

km_results <- kmeans(price_matrix_valid,3, nstart = 25)
km_results;

#Scale data
pmv_scaled <- scale(price_matrix_valid)

set.seed(123)
km.price <- kmeans(scale(price_matrix_valid), 4, nstart = 25)
library("factoextra")
fviz_cluster(km.price, data = pmv_scaled,
             palette = c("#00AFBB","#2E9FDF", "#E7B800", "#FC4E07"),
             ggtheme = theme_minimal(),
             main = "Partitioning Clustering Plot"
             )
```

```{r elbow}
library(factoextra)
library(NbClust)

fviz_nbclust(price_matrix_valid, kmeans, method = "wss") +
  geom_vline(xintercept = 4, linetype = 2) + # add line for better visualisation
  labs(subtitle = "Elbow method") # add subtitle


```

```{r Silhouette }
fviz_nbclust(price_matrix_valid, kmeans, method = "silhouette") +
  labs(subtitle = "Silhouette method")
```

```{r NbClust}
nbclust_out <- NbClust(
  data = price_matrix_valid,
  distance = "euclidean",
  min.nc = 2, # minimum number of clusters
  max.nc = 4, # maximum number of clusters
  method = "kmeans" # one of: "ward.D", "ward.D2", "single", "complete", "average", "mcquitty", "median", "centroid", "kmeans"
)

```
```{r}
library(cluster)
set.seed(42)
km.price <- kmeans(price_matrix_valid, centers = 3, nstart = 20)

sil <- silhouette(km.price$cluster, dist(price_matrix_valid))

fviz_silhouette(sil)
```

```{r dataquality}
# There are 816 NAs in cpt_hcpcs col
colSums(is.na(charges_wide))

library(skimr)
charges_wide %>% skim()


```

```{r plot-qc1}
# Quick visualizations
ggplot(data = charges_wide) +
  geom_histogram(mapping = aes(x = price), binwidth = 1000) +
  labs(subtitle = "Wide Data")

ggplot(data = charges_long) +
  geom_histogram(mapping = aes(x = charge), binwidth = 1000) +
  labs(subtitle = "Long Data")

ggplot(data = charges_long, mapping = aes(x = charge, y = ..density..)) + 
  geom_freqpoly(mapping = aes(color = payor), binwidth = 10000) +
  theme(legend.position="none") +
  labs(subtitle = "Long Data")

```

```{r plot-heatmap}
charges_long %>%
  count(charge, payor) %>%  
  ggplot(mapping = aes(x = payor, y = charge)) +
    geom_tile(mapping = aes(fill = n))  +
  labs(subtitle = "Long Data")
```

```{r scatter}
ggplot(data = charges_long) +
  geom_point(mapping = aes(x = price, y = charge), alpha = 1 / 100) +
  labs(subtitle = "Long Data")
```
```{r hexbin}
ggplot(data = charges_long) +
  geom_bin2d(mapping = aes(x = price, y = charge)) +
  labs(subtitle = "Long Data")

```

```{r}
# install.packages("hexbin")
ggplot(data = charges_long) +
  geom_hex(mapping = aes(x = payor, y = charge), bins = 60) +
  labs(subtitle = "Long Data")
```



```{r payors-tbl}
# REMEMBER TO FILTER VALUES > 0
payors <- charges_long2 %>%
  select(payor, charge, cpt_hcpcs, charge_description)
```

```{r}
ggplot(data = payors) +
  geom_point(mapping = aes(x = payor, y = charge), alpha = 1 / 100) +
    labs(subtitle = "Payors - Long Data")
```

```{r na-payors}
payor_ct <- payors %>% 
  group_by(payor) %>% 
  count(payor) %>% 
  arrange(desc(n)) %>%
  filter(n < 100)

ggplot(data = payor_ct) +
  geom_col(mapping = aes(x = payor, y = n))

```

