```{r setup, echo=FALSE}

library(tidyverse)
library(janitor)
library(hrbrthemes)
# library(ggridges)
library(ggrepel)
# library(haven)
library(DataExplorer)
library(stringi)
library(viridis)
library(ggrepel)

# charges_21 <- read_csv("data/561118388_uncmedicalcenter_cdmstandardcharges.csv",
#                     #clean column names
#                     name_repair = make_clean_names)
# 
# charges_22 <- read_csv("../data/561118388_uncmedicalcenter_standardcharges_22.csv",
#                     #clean column names
#                     name_repair = make_clean_names)


simple_21 <- read_csv("../data/561118388_uncmedicalcenter_cdmstandardcharges.csv", col_select = c("charge_description":"max"),
                    #clean column names
                    name_repair = make_clean_names)

simple_21 <- simple_21 %>%
  rename(charge = price,
         minimum = min,
         maximum = max) %>%
  mutate(charge = parse_number(as.character(charge))) %>%
  mutate(minimum = parse_number(as.character(minimum))) %>%
  mutate(maximum = parse_number(as.character(maximum))
         )

simple_22 <- read_csv("../data/561118388_uncmedicalcenter_standardcharges_22.csv", col_select = c("charge_description":"de_identified_maximum_negotiated_charge"),
                    #clean column names
                    name_repair = make_clean_names)

simple_22 <- simple_22 %>%
  rename(
    minimum = de_identified_minimum_negotiated_charge, 
    maximum = de_identified_maximum_negotiated_charge) %>%
  mutate(charge = parse_number(as.character(charge))) %>%
  mutate(minimum = parse_number(as.character(minimum))) %>%
  mutate(maximum = parse_number(as.character(maximum))
         )

print(sprintf("The 2022 chargemaster contains %d service charges, while 2021 contains only %d (%0.2f %% increase from last year)",
              nrow(simple_22),
              nrow(simple_21),
              100-100*nrow(simple_21)/nrow(simple_22)));

```

```{r clean-import}
library(tidyverse)
library(janitor)
library(hrbrthemes)

# specify  directory, then read a list of files
file_path <- here::here("data/")
file_list <- fs::dir_ls(file_path, regexp = ".csv$")

# return a single data frame, combine data
df_source = file_list |>
  purrr::map_dfr(read_csv, .id = "source") |>
  clean_names()

# add column for year based on source
df_source$year <- with(df_source, ifelse(source == "C:/Users/akant/Documents/unch-charges/data/561118388_uncmedicalcenter_cdmstandardcharges.csv", 2021, 2022))

# gather 2021 data
df_clean21 <- df_source |>
  mutate(
    charge_description = str_remove_all(charge_description, "HC "),
    charge = parse_number(as.character(charge)),
    price = parse_number(as.character(price)),
    min = parse_number(as.character(min)),
    max = parse_number(as.character(max))) |>
    select(year, charge_description, cpt_hcpcs, price, min, max) |>
    filter(year == 2021
      )

# gather 2022 data and clean cols
df_clean22 <- df_source |>
  mutate(
    price = parse_number(as.character(charge)),
    min = parse_number(as.character(de_identified_minimum_negotiated_charge)),
    max = parse_number(as.character(de_identified_maximum_negotiated_charge)),
    charge_description = str_remove_all(charge_description, "HC ")) |>
    select(year,
         charge_description,
         cpt_hcpcs,
         price,
         min,
         max) |>
    filter(year == 2022)
  
# merge long
df_diff <- bind_rows(df_clean22, df_clean21)

# calculate percent change
df_percent <- df_diff %>%
  arrange(charge_description, year) %>%
  group_by(charge_description) %>%
  mutate(percent_change = (last(price) - first(price))/first(price),
         min_change = (last(min) - first(min))/first(min),
         max_change = (last(max) - first(max))/first(max)) %>%
  ungroup()




```














```{r eda-comp}
# Plot missing row values
plot_missing(simple_21)
plot_missing(simple_22)

# Analyze missing values between datasets
miss21 <- profile_missing(simple_21)
miss22 <- profile_missing(simple_22)

print(sprintf("The 2022 chargemaster contains %d missing codes and 2021 has %d missing codes",
              miss22[[2,2]],
              miss21[[2,2]]));

rm(miss21)
rm(miss22)
```

PLOTTING

-JOIN ON CPT_HCPCS, CHARGE_DESCRPITION
x = simple_22, y = simple_21
Check row losses

print(sprintf("Before inner join: %d, after %d (%0.2f %% decrease)",
              nrow(x),
              nrow(y),
              100-100*nrow(y)/nrow(x)));
              
MUTATE NEW COL (22/21)/
            mutate(pct_change = ((Profit/lag(Profit) - 1) * 100))
            
            
            pct <- function(x) {x / lag(x) - 1}
            df_vertical_growth %>% group_by(YEAR, VERTICAL) %>% mutate_at(funs=pct,Profit)
            
DROP OTHER COLUMNS
SLICE MIN MAX 10
GGPLOT

```{r}
compare <- simple_21 %>%
  inner_join(simple_22, c("cpt_hcpcs", "charge_description"), na_matches = "never", keep = T, suffix = c(".21",".22"))

df_compare <- simple_22 %>%
  left_join(simple_21, by = "charge_description", na_matches = "never", keep = T, suffix = c(".22",".21"))

# Clean up
rm(simple_21, simple_22)

plot_missing(compare)
plot_missing(df_compare)

# Remove 'HC ' string from descriptions
df_compare <- modify_at(df_compare, c(1, 6),  ~str_remove_all(.,"HC "))

df_diff <- df_compare %>%
  drop_na() %>%
  mutate(pct_change = ((charge.22 - charge.21) / charge.21) * 100) %>%
  mutate(abs_change = charge.22 - charge.21) %>%
  select(description = charge_description.22,
         code = cpt_hcpcs.22,
         pct_change,
         abs_change,
         charge.22,
         charge.21) %>%
  distinct()
```



```{r plot}
# library
library(ggplot2)
library(dplyr)

# Add a column with your condition for the color
# df_plot <- df_diff %>% 
#   mutate(mycolor = ifelse(pct_change>0, "type1", "type2")) %>%
#   tibble::rownames_to_column(var = "x") %>%
#   arrange(x, pct_change) %>%
#   group_by(pct_change) %>%
#   mutate(rank=row_number(pct_change))


# %>%
#   mutate(rank = min_rank(-pct_change))

  # mutate(x=dense_rank(desc(-pct_change)))

  # mutate(x = row_number(pct_change))
  
# x <- seq(0, 2*pi, length.out=1000)

# df_plot <- df_slice %>% 
#   mutate(mycolor = ifelse(pct_change>0, "type1", "type2")) %>%
#   tibble::rownames_to_column(var = "x") %>%
#   arrange(x, desc(-pct_change))


# plot
df_slice <- bind_rows(
  df_diff %>% slice_min(pct_change, n=10, with_ties = FALSE),
  df_diff %>% slice_max(pct_change, n=10, with_ties = FALSE)
)

df_plot <- df_slice %>% 
  mutate(mycolor = ifelse(pct_change>0, "type1", "type2")) %>%
  tibble::rownames_to_column(var = "index") %>%
  arrange(pct_change) %>%
  mutate(description=factor(description, description))

# %>%
#   arrange(desc(pct_change))

# df_plot <- transform(df_plot, x = fct_shuffle(df_plot$x))

# Saving df_diff to other project
# write.csv(df_diff, file = "C:\\Users\\akant\\Documents\\blog\\content\\post\\2022-07-03-why-healthcare-pricing-transparncy-is-hard\\df_dff.csv")



# df_plot
```


```{r final-plot, warning=FALSE, message=F}

ggplot(data = df_plot, aes(description, pct_change)) +
    geom_hline(
    yintercept = 100,
    colour = "red",
    size = 0.7,
    alpha = 0.35, 
    linetype = "dashed"
  ) +
    geom_hline(
    yintercept = 200,
    colour = "red",
    size = 0.7,
    alpha = 0.35, 
    linetype = "dashed"
  ) +
  geom_hline(
    yintercept = 0,
    colour = "darkgrey",
    size = 0.7,
    alpha = 1
  ) +
  geom_segment(
    aes(
      x = description,
      xend = description,
      y = 0,
      yend = pct_change,
      color = mycolor
    ),
    size = 9,
    alpha = 1,
  ) +
  scale_y_continuous(labels = scales::percent_format(scale = 1), expand = expansion(mult = c(.05, NA))) +
  geom_label(
    aes(label = description),
    alpha = 0,
    hjust = "inward",
    # position = position_stack(vjust = 0),
    size = 4.5,
    label.size = 0,
    label.padding = unit(0.2, "lines")) +
  geom_text(
    aes(label = scales::dollar(charge.22)),
    hjust = "outward"
  ) +
  theme_ipsum_rc() +
  labs(
    title = "Top/Bottom 10 Pricing Changes for Healthcare Services",
    subtitle = "UNC Medical Center | July 2022",
    x = "",
    y = "Relative Percent Change 2022-2021 (%) | Listed Cost 2022 ($)",
    caption = "Source | UNC Health"
  ) +
  theme(
    plot.margin = margin(15, 40, 8, 8),
    panel.grid.minor.y = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    axis.title.x = element_text(hjust=0, vjust = -0.2),
    axis.ticks.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks.y = element_blank(),
    legend.position = "none",
    panel.border = element_blank()) +
  coord_flip(clip = "off") +
  guides(fill = guide_legend(override.aes = list(alpha = 1))
  )

# ggsave("images/charge-movers22.png", bg = "white")
# ggsave("images/charge-movers22.png", bg = "white", width = 10, height = 10, units = "in", dpi = 300)

```




































## SCRATCH 

```{r convert-numeric}
charges_long_21 <- charges_21 %>%
  # Wrangle payor columns to key:value pair
  pivot_longer(
    cols = aetna:united_healthcare_medicare_advantage,
    names_to = "payor",
    values_to = "charge_payor",
    )

charges_long_22 <- charges_22 %>%
  # Wrangle payor columns to key:value pair
  pivot_longer(
    cols = discounted_cash_price:well_care_medicare_advantage,
    names_to = "payor",
    values_to = "charge_payor",
    )

charges_long_21$price = as.integer(gsub("[\\$,]", "", charges_long_21$price))
charges_long_21$min = as.integer(gsub("[\\$,]", "", charges_long_21$min))
charges_long_21$max = as.integer(gsub("[\\$,]", "", charges_long_21$max))
charges_long_21$charge_payor = as.integer(gsub("[\\$,]", "", charges_long_21$charge_payor))

charges_long_22$charge = as.integer(gsub("[\\$,]", "", charges_long_22$charge))
charges_long_22$de_identified_minimum_negotiated_charge = as.integer(gsub("[\\$,]", "", charges_long_22$de_identified_minimum_negotiated_charge))
charges_long_22$de_identified_maximum_negotiated_charge = as.integer(gsub("[\\$,]", "", charges_long_22$de_identified_maximum_negotiated_charge))
charges_long_22$charge_payor = as.integer(gsub("[\\$,]", "", charges_long_22$charge_payor))


charges_num_21 <- charges_long_21 %>%
                  select(-facility_name) %>%
                  pivot_wider(names_from = "payor",
                    values_from = "charge_payor",
                    names_glue="{.value}_{payor}",
                    values_fill=0) %>%
                  mutate(index_cluster=1:nrow(.)) %>%
                  arrange(runif(nrow(.)));

charges_num_22 <- charges_long_22 %>%
                  select(-facility_name) %>%
                  pivot_wider(names_from = "payor",
                    values_from = "charge_payor",
                    names_glue="{.value}_{payor}",
                    values_fill=0) %>%
                  mutate(index_cluster=1:nrow(.)) %>%
                  arrange(runif(nrow(.)));

charges_num_22 <- charges_long_22 %>%
                  select(-facility_name) %>%
                  mutate(index_cluster = row_number()) %>%
                  pivot_wider(names_from = "payor",
                    values_from = "charge_payor")

rm(charges_21)
rm(charges_22)
rm(charges_long_21)
rm(charges_long_22)

# tmp <- df_diff |>
#   group_by(year) |>
#     mutate(price_lag = lag(price),
#            diff = price - price_lag) |>
#     na.omit() |>
#   ungroup() |>
#   mutate(percentage = diff/price_lag)

# df_diff$pct <- (df_diff$year - charge.21) / charge.21) * 100)

# compare data charge differences
tmp <- df_diff %>%
  drop_na(price) |>
  distinct() |>
  select(price, year, charge_description) |>
  group_by(year, price) |>
  mutate(
    Count = scales::percent(price))

tmp <- df_diff |>
  group_by(year) |>
  mutate(per = prop.table(count) * 100)



  
  
  
  mutate(yoy_perc = ((charge.22 - charge.21) / charge.21) * 100) %>%
  mutate(yoy_abs = charge.22 - charge.21) %>%
  select(description = charge_description.22,
         code = cpt_hcpcs.22,
         pct_change,
         abs_change,
         charge.22,
         charge.21) %>%
  distinct()

df_diff




# clean_data <- source_data |>
#   clean_names() |>
#   select(
#     source,
#     charge_description,
#     cpt_hcpcs,
#     price,
#     min,
#     max,
#     de_identified_minimum_negotiated_charge,
#     de_identified_maximum_negotiated_charge
#   ) |>
#   rename(min = 21)
        

```

```{r}
# OBSELETE WRANGLING
df_diff <- df_compare %>%
  mutate(charge.22 = parse_number(as.character(charge.22))) %>%
  mutate(minimum.22 = parse_number(as.character(minimum.22))) %>%
  mutate(maximum.22 = parse_number(as.character(minimum.22))) %>%
      mutate(charge.21 = parse_number(as.character(charge.21))) %>%
      mutate(minimum.21 = parse_number(as.character(minimum.21))) %>%
      mutate(maximum.21 = parse_number(as.character(maximum.21))) %>%
      distinct() %>%
      drop_na() %>%
      mutate(pct_change = ((
        charge.22 - charge.21
      ) / charge.21) * 100) %>%
      mutate(abs_change = charge.22 - charge.21) %>%
      select(
        charge_description.22,
        code = cpt_hcpcs.22,
        pct_change,
        abs_change,
        charge.22,
        charge.21
      )



# print(sprintf("There is a  %d percent difference between charges before join, after %d (%0.2f %% decrease)",
#             (nrow(simple_22)/nrow(simple_21) - 1) *100,
#               nrow(simple_21),
#               nrow(compare),
#               100-100*nrow(compare)/nrow(simple_21)));
# 
# pct_change = ((Profit/lag(Profit) - 1) * 100))


# Remove 'HC ' string from all descriptions OBSELETE, MODIFY REMOVES ATTR
df_compare2 <- modify(df_compare, ~str_remove_all(.,"HC "))

simple_21[, col_list] <-
  lapply(simple_21[, col_list], function(x)
    x <- car::recode(x, "charge"=as.numeric(); "min"=as.numeric(); "max"=as.numeric())
```
 
```{r backup-plot}

ggplot(data = df_plot, aes(description, pct_change)) +
  geom_segment(
    aes(
      x = description,
      xend = description,
      y = 0,
      yend = pct_change,
      color = mycolor
    ),
    size = 7,
    alpha = 0.7,
  ) +
  scale_y_continuous(expand = expansion(mult = c(.2, NA))) + 
  geom_label(
    aes(label = description),
    alpha = 0, 
    hjust = "inward",
    position = position_stack(vjust = 0),
    size = 3,
    # fill = mycolor,
    label.size = 0, 
    label.padding=unit(0.2, "lines"))+
  # geom_label(aes(label = description), hjust = "inward", size = 2.5,
  #               fill = "white", label.size = 0) +
  # geom_label_repel(aes(label = description),
  #   data = df_plot,
  #   size = 1,
  #   label.size = 0,
  #   segment.color = NA
  # ) +
)
  theme_ipsum_rc() +
  labs(title = "Year-over-Year Change in Healthcare Services",
       subtitle="UNC Medical Center",
       x = "",
       y = "Percent Change 2022 to 2021",
       caption = "Source | UNC Health") + 
  # scale_x_discrete(expand = c(0, 0)) +
  # scale_y_continuous(expand = c(0,NA)) + 
  scale_fill_viridis(option = "C", discrete = TRUE) +
  theme(
    plot.margin = margin(rep(15, 4)),
    panel.grid.minor.y = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    axis.text.x=element_blank(),
    axis.ticks.x=element_blank(),
    axis.text.y=element_text(),
    axis.ticks.y=element_blank(), 
    legend.position = "none",
    panel.border = element_blank(),
    # plot.margin = margin(rep(15, 4))
  ) +
  coord_flip(clip = "off") +
  geom_hline(yintercept = 100, colour = "red", size = 0.7, alpha = 0.7) +
  geom_hline(yintercept = 0, colour = "darkslategrey", size = 0.7, alpha = 0.7) +
  guides(fill = guide_legend(override.aes = list(alpha = 1))
         )


# scales::percent
# (clip = "off")

      # guides(x = guide_axis(angle = -20)) +
      # theme_ipsum_rc()
```
 
```{r functions}

csv_clean <- function(x) {
  df <- lapply()
  # df <- select({{ var }}, c(2:6))
}

csv_clean(source_data)

x <- 10
f1 <- function(x) {
  function() {
    x + 10
  }
}
f1(1)()
```
 
 